apiVersion: apps/v1
kind: Deployment
metadata:
  name: chat-inference-GIT_BRANCH
spec:
  selector:
    matchLabels:
      app: chat-inference-GIT_BRANCH
  replicas: 1
  template:
    metadata:
      labels:
        org: tz
        team: devops
        environment: STAGING
        app: chat-inference-GIT_BRANCH
    spec:
      imagePullSecrets:
        - name: tz-registrykey
      containers:
      - name: chat-inference-GIT_BRANCH
        image: doohee323/chat-inference:BUILD_NUMBER_PLACEHOLDER
        imagePullPolicy: Always
        ports:
        - containerPort: 8088
        readinessProbe:
          httpGet:
            path: /health
            port: 8088
        livenessProbe:
          httpGet:
            path: /health
            port: 8088
          initialDelaySeconds: 10
          periodSeconds: 30
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 500m
            memory: 512Mi
        envFrom:
        - configMapRef:
            name: chat-inference-configmap-GIT_BRANCH
        - secretRef:
            name: chat-inference-secret-GIT_BRANCH

---
apiVersion: v1
kind: Service
metadata:
  name: chat-inference-GIT_BRANCH
spec:
  type: NodePort
  selector:
    app: chat-inference-GIT_BRANCH
  ports:
  - port: 80
    name: http
    targetPort: 8088

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: chat-inference-configmap-GIT_BRANCH
data:
  ALLOWED_SYSTEM_IDS: "drillquiz,cointutor"
  ALLOWED_CHAT_TOKEN_ORIGINS: ""
  POSTGRES_HOST: "devops-postgres-postgresql.devops.svc.cluster.local"
  POSTGRES_PORT: "5432"
  POSTGRES_DB: "chat_admin"
  POSTGRES_USER: "postgres"
  CHAT_ADMIN_URL: "http://chat-admin-GIT_BRANCH.devops.svc.cluster.local"
  RAG_BACKEND_URL: "http://rag-backend.rag.svc.cluster.local:8000"

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: chat-inference-GIT_BRANCH
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    nginx.ingress.kubernetes.io/proxy-connect-timeout: "5"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "300"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "300"
spec:
  ingressClassName: nginx
  rules:
  - host: chat-inference-qa.DOMAIN_PLACEHOLDER
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: chat-inference-GIT_BRANCH
            port:
              number: 80
  tls:
    - hosts:
        - chat-inference-qa.DOMAIN_PLACEHOLDER
      secretName: chat-inference-GIT_BRANCH

---
apiVersion: v1
kind: Secret
metadata:
  name: chat-inference-secret-GIT_BRANCH
type: Opaque
data:
  CHAT_GATEWAY_JWT_SECRET: #CHAT_GATEWAY_JWT_SECRET
  CHAT_GATEWAY_API_KEY: #CHAT_GATEWAY_API_KEY
  POSTGRES_PASSWORD: #POSTGRES_PASSWORD
  GEMINI_API_KEY: #GEMINI_API_KEY

---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: chat-inference-hpa-GIT_BRANCH
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: chat-inference-GIT_BRANCH
  minReplicas: 1
  maxReplicas: 2
  targetCPUUtilizationPercentage: 70
