apiVersion: apps/v1
kind: Deployment
metadata:
  name: chat-inference
spec:
  selector:
    matchLabels:
      app: chat-inference
  replicas: 2
  minReadySeconds: 30
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  template:
    metadata:
      labels:
        org: tz
        team: devops
        environment: main
        app: chat-inference
    spec:
      imagePullSecrets:
        - name: tz-registrykey
      containers:
      - name: chat-inference
        image: doohee323/chat-inference:BUILD_NUMBER_PLACEHOLDER
        imagePullPolicy: Always
        ports:
        - containerPort: 8088
        readinessProbe:
          httpGet:
            path: /health
            port: 8088
          initialDelaySeconds: 10
          periodSeconds: 10
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 3
        livenessProbe:
          httpGet:
            path: /health
            port: 8088
          initialDelaySeconds: 30
          periodSeconds: 30
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 3
        resources:
          limits:
            cpu: 1
            memory: 512Mi
          requests:
            cpu: 100m
            memory: 256Mi
        envFrom:
        - configMapRef:
            name: chat-inference-configmap-GIT_BRANCH
        - secretRef:
            name: chat-inference-secret-GIT_BRANCH

---
apiVersion: v1
kind: Service
metadata:
  name: chat-inference
spec:
  type: NodePort
  selector:
    app: chat-inference
  ports:
  - port: 80
    name: http
    targetPort: 8088

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: chat-inference-configmap-GIT_BRANCH
data:
  ALLOWED_SYSTEM_IDS: "drillquiz,cointutor"
  ALLOWED_CHAT_TOKEN_ORIGINS: ""
  POSTGRES_HOST: "devops-postgres-postgresql.devops.svc.cluster.local"
  POSTGRES_PORT: "5432"
  POSTGRES_DB: "chat_admin"
  POSTGRES_USER: "postgres"
  CHAT_ADMIN_URL: "http://localhost:8080"
  RAG_BACKEND_URL: "http://rag-backend.rag.svc.cluster.local:8000"

---
apiVersion: v1
kind: Secret
metadata:
  name: chat-inference-secret-GIT_BRANCH
type: Opaque
data:
  CHAT_GATEWAY_JWT_SECRET: #CHAT_GATEWAY_JWT_SECRET
  CHAT_GATEWAY_API_KEY: #CHAT_GATEWAY_API_KEY
  POSTGRES_PASSWORD: #POSTGRES_PASSWORD
  GEMINI_API_KEY: #GEMINI_API_KEY
