# RAG Backend DrillQuiz only (approach A: two backends)
# ConfigMap rag-backend-drillquiz-script, Secret rag-ingestion-secret-drillquiz (each DrillQuiz-specific)
# COLLECTION=rag_docs_drillquiz fixed
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: rag-backend-drillquiz-script
  namespace: rag
data:
  main.py: |
    from fastapi import FastAPI, HTTPException, Request
    from fastapi.responses import JSONResponse
    from pydantic import BaseModel
    import os
    import uvicorn
    from langchain_google_genai import GoogleGenerativeAIEmbeddings
    from langchain_qdrant import QdrantVectorStore
    from slowapi import Limiter, _rate_limit_exceeded_handler
    from slowapi.util import get_remote_address
    from slowapi.errors import RateLimitExceeded

    limiter = Limiter(key_func=get_remote_address)
    app = FastAPI(title="RAG Backend DrillQuiz")
    app.state.limiter = limiter
    app.add_exception_handler(RateLimitExceeded, _rate_limit_exceeded_handler)
    QDRANT_HOST = os.environ.get("QDRANT_HOST", "qdrant")
    QDRANT_PORT = int(os.environ.get("QDRANT_PORT", "6333"))
    COLLECTION = os.environ.get("QDRANT_COLLECTION", "rag_docs_drillquiz")
    GEMINI_KEY = os.environ.get("GEMINI_API_KEY") or os.environ.get("GOOGLE_API_KEY")
    EMBED_MODEL = os.environ.get("EMBEDDING_MODEL", "gemini-embedding-001")
    QDRANT_URL = f"http://{QDRANT_HOST}:{QDRANT_PORT}"

    def get_vector_store(collection_name: str):
        if not GEMINI_KEY:
            raise ValueError("GEMINI_API_KEY or GOOGLE_API_KEY required")
        embeddings = GoogleGenerativeAIEmbeddings(
            model=EMBED_MODEL,
            google_api_key=GEMINI_KEY,
            task_type="retrieval_query",
            output_dimensionality=1536,
        )
        return QdrantVectorStore.from_existing_collection(
            embedding=embeddings,
            url=QDRANT_URL,
            collection_name=collection_name,
            prefer_grpc=False,
        )

    class QueryRequest(BaseModel):
        question: str
        top_k: int = 5
        collection: str | None = None

    @app.get("/health")
    def health():
        return {"status": "ok"}

    @app.post("/query")
    @limiter.limit(os.environ.get("RATE_LIMIT_QUERY", "20/minute"))
    def query(req: QueryRequest, request: Request):
        try:
            question = (req.question or "").strip() or ""
            coll = (req.collection or "").strip() or COLLECTION
            if not question:
                body = {"question": question, "results": []}
                return JSONResponse(content=body, headers={"Cache-Control": "no-store, no-cache, must-revalidate, max-age=0"})
            vs = get_vector_store(coll)
            docs_with_scores = vs.similarity_search_with_score(question, k=req.top_k)
            results = [
                {
                    "text": doc.page_content,
                    "source": doc.metadata.get("source", ""),
                    "path": doc.metadata.get("path", ""),
                    "score": float(score) if score is not None else None,
                }
                for doc, score in docs_with_scores
            ]
            body = {"question": question, "results": results}
            return JSONResponse(
                content=body,
                headers={"Cache-Control": "no-store, no-cache, must-revalidate, max-age=0"},
            )
        except Exception as e:
            raise HTTPException(status_code=500, detail=str(e))

    if __name__ == "__main__":
        uvicorn.run(app, host="0.0.0.0", port=8000)
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rag-backend-drillquiz
  namespace: rag
  labels:
    app: rag-backend-drillquiz
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rag-backend-drillquiz
  template:
    metadata:
      labels:
        app: rag-backend-drillquiz
    spec:
      containers:
      - name: backend
        image: python:3.11-slim
        command: ["/bin/sh", "-c"]
        args:
        - |
          pip install --no-cache-dir fastapi uvicorn langchain-qdrant langchain-google-genai slowapi 2>/dev/null
          cp /config/main.py /tmp/main.py && exec python /tmp/main.py
        envFrom:
        - secretRef:
            name: rag-ingestion-secret-drillquiz
        env:
        - name: QDRANT_HOST
          value: "qdrant"
        - name: QDRANT_PORT
          value: "6333"
        - name: QDRANT_COLLECTION
          value: "rag_docs_drillquiz"
        - name: EMBEDDING_MODEL
          value: "gemini-embedding-001"
        volumeMounts:
        - name: config
          mountPath: /config
          readOnly: true
        ports:
        - containerPort: 8000
        resources:
          requests:
            memory: "512Mi"
            cpu: "100m"
          limits:
            memory: "2Gi"
            cpu: "1000m"
      volumes:
      - name: config
        configMap:
          name: rag-backend-drillquiz-script
---
apiVersion: v1
kind: Service
metadata:
  name: rag-backend-drillquiz
  namespace: rag
spec:
  selector:
    app: rag-backend-drillquiz
  ports:
  - port: 8000
    targetPort: 8000
    name: http
